### ISSUE TITLE
ValueError: Axis limits cannot be NaN or Inf

### ISSUE THREAD

**Issue by Shaibuli** [VUB-HYDR/RSAT#3]
Hi,

I've been tring to get RSAT to work for a couple of days now, but unfortunately always run into the same error when trying to plot the datafile.

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "G:\Python379\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "RSAT.py", line 58, in PlotDataSeperateBox
    plt.axis([self.dfRAWDATA.iloc[0,0]-len(self.dfRAWDATA)/60,self.dfRAWDATA.iloc[-1,0]+len(self.dfRAWDATA)/60,min(self.dfRAWDATA.iloc[:,3])-20,max(self.dfRAWDATA.iloc[:,3])+20])
  File "G:\Python379\lib\site-packages\matplotlib\pyplot.py", line 2371, in axis
    return gca().axis(*args, emit=emit, **kwargs)
  File "G:\Python379\lib\site-packages\matplotlib\axes\_base.py", line 2097, in axis
    self.set_ylim(ymin, ymax, emit=emit, auto=yauto)
  File "G:\Python379\lib\site-packages\matplotlib\axes\_base.py", line 4027, in set_ylim
    bottom = self._validate_converted_limits(bottom, self.convert_yunits)
  File "G:\Python379\lib\site-packages\matplotlib\axes\_base.py", line 3614, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf
```
I've tried running the code on the latest Python 3.12.2 as well as Python 3.7.9, but both produce pretty much the same error (the above is on 3.7.9). I've also installed matplotlib, pandas and tkinter as those seem to be used in the code.

I've tried to follow the manual rigorously when it comes to the data file formatting and I've tried multiple ways of formatting my file always ending up with the same error. My best effort can be fould within the [RSAT_Shaibuli.zip](https://github.com/VUB-HYDR/RSAT/files/14801039/RSAT_Shaibuli.zip) -file. I would really like to encourage @HMEUW to continue with the documentation work he's been doing, as the user manual could do with some 'for dummies' type of explanation. e.g. a screen capture of the correct data formatting and a picture/illustration on what the different slug test characteristics actually match. Maybe I can even get into helping him at some point, if I get a better hang of things first.

My github and python skills are novice at best, so it might turn out that the solution is something really simple and stupid. It's really unfortunate, however, that it seems so hard for a noobie to get this working. The world of hydrogeology could really do with a freely accessible, quality tool for slug test interpretation as slug-tests themselves are a pretty great minimum-budget method for e.g. developing nations to do basic hydrogeological characterisation.

Thank you!

**Comment by HMEUW** [comment]
Hi Shaibuli. Thanks for mentioning me. 

In the mean time I worked a lot on slugtest execution and interpretation. I didn't spend time in the RSAT functions. I have plans to share the functions with the world, but decided first to develop these.

**Comment by MattBrst** [comment]
Hi Shaibuli. 

I agree with you on the value of an open source repository which is able to handle the Hvorslev approach (which potentially RSAT could be). 

You might take a look at TTim with the well-documented slugtest example [Pratt County](https://ttim.readthedocs.io/en/latest/04pumpingtests/slug1_pratt_county.html). Although this is not exactly what you ask for, this might help you to get a first estimate of your conductivity while also being able to experiment with Python.
